server:
  port: 3020
spring:
  application:
    name: route
eureka:
  client:
    serviceurl:
      defaultZone: http://peer1:1000/eureka/

zuul.routes.api-a.path: /api-a/**
zuul.routes.api-a.serviceId: user
zuul.routes.api-b.path: /api-b/**
zuul.routes.api-b.serviceId: feign

feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon.ConnectTimeout: 60000
ribbon.ReadTimeout: 60000

user.ribbon.ConnectTime: 60000
user.ribbon.ReadTimeout: 60000
user.ribbon.OkToRetryOnAllOperations: true
user.ribbon.MaxAutoRetriesNextServer: 2
user.ribbon.MaxAutoRetries: 1
zuul:
  retryable: false
  routes.user.retryable: false